/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui_employee;

import aed_assignment_1.employee_list;
import aed_assignment_1.employee_profile;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author shubhambagal
 */
public class Create_employee1 extends javax.swing.JPanel {

    /**
     * Creates new form Create_employee1
     */
    
    String path;
    employee_list e_list;
    public Create_employee1(employee_list employee_list) {
        initComponents();
        this.e_list = employee_list;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_grp = new javax.swing.ButtonGroup();
        label_employee = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_start_date = new javax.swing.JLabel();
        lbl_level = new javax.swing.JLabel();
        lbl_team = new javax.swing.JLabel();
        lbl_position = new javax.swing.JLabel();
        lbl_cell = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_start = new javax.swing.JTextField();
        txt_team = new javax.swing.JTextField();
        txt_poition = new javax.swing.JTextField();
        txt_cell = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        txt_photo = new javax.swing.JButton();
        txt_level = new javax.swing.JComboBox<>();

        label_employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_employee.setText("Create Employee Profile");

        lbl_name.setText("Name");

        lbl_ID.setText("ID");

        lbl_age.setText("Age");

        lbl_gender.setText("Gender");

        lbl_start_date.setText("Start Date");

        lbl_level.setText("Level");

        lbl_team.setText("Team Info");

        lbl_position.setText("Potition Title");

        lbl_cell.setText("Cell Phone");

        lbl_email.setText("Email Address");

        lbl_photo.setText("Photo");

        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });

        txt_team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teamActionPerformed(evt);
            }
        });

        txt_poition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_poitionActionPerformed(evt);
            }
        });

        txt_cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cellActionPerformed(evt);
            }
        });
        txt_cell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cellKeyTyped(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        btn_create.setText("Save");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        gender_grp.add(radio_male);
        radio_male.setText("Male");
        radio_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_maleActionPerformed(evt);
            }
        });

        gender_grp.add(radio_female);
        radio_female.setText("Female");
        radio_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_femaleActionPerformed(evt);
            }
        });

        txt_photo.setText("Browse");
        txt_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_photoActionPerformed(evt);
            }
        });

        txt_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Level-", "Junior", "Level 2", "Level 3", "Senior", "Manager", "Sr Maneger", "Associate" }));
        txt_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_levelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_photo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_photo)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cell, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_position)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_poition, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_team)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_team, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addGap(88, 88, 88)
                        .addComponent(txt_name))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_create)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_age)
                            .addComponent(lbl_gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(radio_male, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radio_female))
                            .addComponent(txt_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_start_date)
                            .addComponent(lbl_level))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_start, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txt_level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(label_employee, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ID)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_age)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_gender)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_male, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radio_female)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_start_date)
                    .addComponent(txt_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_level)
                    .addComponent(txt_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_team)
                    .addComponent(txt_team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_position)
                    .addComponent(txt_poition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cell))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_photo)
                    .addComponent(txt_photo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btn_create)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_teamActionPerformed

    private void txt_poitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_poitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_poitionActionPerformed

    private void txt_cellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cellActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // TODO add your handling code here:
     String name = txt_name.getText()  ;
     String gender;
     String id=txt_id.getText();
     int age = Integer.parseInt(txt_age.getText().trim());
     if(radio_female.isSelected()){
          gender = "Female";
     }
     else{
         gender = "Male";
     }
     String start_date = txt_start.getText();
     String level= txt_level.getSelectedItem().toString();
     String team_info = txt_team.getText();
     String position = txt_poition.getText();
     long phone = Integer.parseInt(txt_cell.getText().trim());
     String email = txt_email.getText();
     
     
     int count = 0;
        while(phone!=0) {
            phone = phone/10; 
            count++;
        }
        if(count!= 10){
            JOptionPane.showMessageDialog(null, "*Please Enter Valid Number");    
            
        }
     
     if(name.equals("")){
        JOptionPane.showMessageDialog(this, "Please Add Name");
     }
     
     else if(gender.equals("")){
         JOptionPane.showMessageDialog(this, "Please Select Gender..");
     }
     else if(id.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add ID..");
     }
    
     else if(start_date.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add Start Date..");
     }
     else if(level.equals("-Select Level-")){
         JOptionPane.showMessageDialog(this, "Please Add Level..");
     }
     else if(team_info.equals("")){
        JOptionPane.showMessageDialog(this, "Please Add Team Info..");
     }
     else if(position.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add Position..");
     }
     else if(path== null){
         JOptionPane.showMessageDialog(this, "Please Add Image..");
     }
     
     
     else if(email.equals("")){
        JOptionPane.showMessageDialog(this, "Please Add E-mail..");
        
  
     }
     
     
     else if(!name.equals("")&& !gender.equals("") && !id.equals("") && !start_date.equals("") && 
             !level.equals("") && !level.equals("") && !level.equals("") && !level.equals("") && !level.equals("") &&
             !level.equals("") && !level.equals("") &&!team_info.equals("")&& !position.equals("") && !email.equals("") && !path.equals("") && count==10)
     {
     employee_profile ep = e_list.addnewEmployee();
     ep.setName(name);
     ep.setAge(age);
     ep.setId(id);
     ep.setLevel(level);
     ep.setStart_date(start_date);
     ep.setTeam_info(team_info);
     ep.setPosition(position);
     ep.setPhone(phone);
     ep.setEmail(email);
     ep.setGender(gender);
     ep.setPhoto(path);
     
     
     JOptionPane.showMessageDialog(this, "New Enployee Added " + path);
     
     txt_name.setText("");
     txt_id.setText("");
     txt_age.setText("");
     txt_start.setText("");
     txt_level.setSelectedIndex(0);
     txt_team.setText("");
     txt_poition.setText("");
     txt_cell.setText("");
     txt_email.setText("");
     gender_grp.clearSelection();
     
     
     }
     
        
      
    }//GEN-LAST:event_btn_createActionPerformed

    private void radio_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_maleActionPerformed

    private void radio_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_femaleActionPerformed

    private void txt_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_photoActionPerformed
        // TODO add your handling code here:
        
        
          JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              path = selectedFile.getAbsolutePath();
              
          }
           //if the user click on save in Jfilechooser


          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
        
   
    }//GEN-LAST:event_txt_photoActionPerformed

    private void txt_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_levelActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_levelActionPerformed

    private void txt_cellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cellKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)) || enter== KeyEvent.VK_BACK_SPACE || enter== KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_cellKeyTyped

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped
        // TODO add your handling code here:
        
         char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)) || enter== KeyEvent.VK_BACK_SPACE || enter== KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_ageKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.ButtonGroup gender_grp;
    private javax.swing.JLabel label_employee;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_cell;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_level;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_position;
    private javax.swing.JLabel lbl_start_date;
    private javax.swing.JLabel lbl_team;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_cell;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JComboBox<String> txt_level;
    private javax.swing.JTextField txt_name;
    private javax.swing.JButton txt_photo;
    private javax.swing.JTextField txt_poition;
    private javax.swing.JTextField txt_start;
    private javax.swing.JTextField txt_team;
    // End of variables declaration//GEN-END:variables
}
