/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui_employee;

import aed_assignment_1.employee_list;
import aed_assignment_1.employee_profile;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author shubhambagal
 */
public class View_employee extends javax.swing.JPanel {

    /**
     * Creates new form View_employee
     */
    
    employee_list e_list;
    public View_employee(employee_list employee_list) {
        initComponents();
        this.e_list = employee_list;
        populate_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_employee_View = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profile_tbl = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_team_v = new javax.swing.JTextField();
        txt_poition_v = new javax.swing.JTextField();
        txt_cell_v = new javax.swing.JTextField();
        txt_email_v = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_start_date = new javax.swing.JLabel();
        lbl_level = new javax.swing.JLabel();
        lbl_team = new javax.swing.JLabel();
        lbl_position = new javax.swing.JLabel();
        lbl_cell = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        txt_name_v = new javax.swing.JTextField();
        txt_id_v = new javax.swing.JTextField();
        txt_age_v = new javax.swing.JTextField();
        txt_start_v = new javax.swing.JTextField();
        txt_level_v = new javax.swing.JTextField();
        txt_gender_v = new javax.swing.JTextField();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        lbl_photo_v = new javax.swing.JLabel();

        label_employee_View.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        label_employee_View.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_employee_View.setText("View Employee Profile");

        profile_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "EMPLOYEE ID", "GENDER", "Team "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(profile_tbl);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_team_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_team_vActionPerformed(evt);
            }
        });

        txt_poition_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_poition_vActionPerformed(evt);
            }
        });

        txt_cell_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cell_vActionPerformed(evt);
            }
        });
        txt_cell_v.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cell_vKeyTyped(evt);
            }
        });

        txt_email_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_vActionPerformed(evt);
            }
        });

        lbl_name.setText("Name");

        lbl_ID.setText("ID");

        lbl_age.setText("Age");

        lbl_gender.setText("Gender");

        lbl_start_date.setText("Start Date");

        lbl_level.setText("Level");

        lbl_team.setText("Team Info");

        lbl_position.setText("Potition Title");

        lbl_cell.setText("Cell Phone");

        lbl_email.setText("Email Address");

        lbl_photo.setText("Photo");

        txt_name_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name_vActionPerformed(evt);
            }
        });

        txt_age_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_age_vActionPerformed(evt);
            }
        });
        txt_age_v.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_age_vKeyTyped(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_gender)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(48, 48, 48))
                                        .addComponent(lbl_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_cell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_team, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_start_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(389, 389, 389)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_email_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_cell_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_poition_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_team_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_level_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_start_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_age_v)
                                    .addComponent(txt_gender_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_name_v)
                                    .addComponent(txt_id_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_photo_v, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(330, 330, 330))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_employee_View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_update)
                                        .addGap(41, 41, 41)
                                        .addComponent(btn_view)
                                        .addGap(37, 37, 37)
                                        .addComponent(btn_delete))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_employee_View)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(btn_view)
                    .addComponent(btn_delete))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ID)
                    .addComponent(txt_id_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_age)
                    .addComponent(txt_age_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_gender)
                    .addComponent(txt_gender_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_start_date)
                    .addComponent(txt_start_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_level)
                    .addComponent(txt_level_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_team)
                    .addComponent(txt_team_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_position)
                    .addComponent(txt_poition_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cell_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cell))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_photo)
                    .addComponent(lbl_photo_v, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
       int selected_row_idx =  profile_tbl.getSelectedRow();
       if(selected_row_idx<0){
           JOptionPane.showMessageDialog(this,"Please select a row to delete");
           return;
       }
        DefaultTableModel model = (DefaultTableModel) profile_tbl.getModel();
       employee_profile select_profile = (employee_profile) model.getValueAt(selected_row_idx,0);
      
       e_list.deleteEmployee(select_profile);
        JOptionPane.showMessageDialog(this,"Vital signs deleted");
          
       populate_table();
       
     
     txt_name_v.setText("");
     txt_id_v.setText("");
     txt_age_v.setText("");
     txt_start_v.setText("");
     txt_level_v.setText("");
     txt_team_v.setText("");
     txt_poition_v.setText("");
     txt_cell_v.setText("");
     txt_email_v.setText("");
     txt_gender_v.setText("");
     lbl_photo_v.setIcon(null);

       
       
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_team_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_team_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_team_vActionPerformed

    private void txt_poition_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_poition_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_poition_vActionPerformed

    private void txt_cell_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cell_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cell_vActionPerformed

    private void txt_email_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_vActionPerformed

    private void txt_age_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_age_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_age_vActionPerformed

    private void txt_name_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_name_vActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
         int selected_row_idx =  profile_tbl.getSelectedRow();
       if(selected_row_idx<0){
           JOptionPane.showMessageDialog(this,"Please select a row to View");
           return;
       }
        DefaultTableModel model = (DefaultTableModel) profile_tbl.getModel();
       employee_profile select_profile = (employee_profile)model.getValueAt(selected_row_idx,0);
       
       txt_name_v.setText(select_profile.getName());
       txt_age_v.setText(String.valueOf(select_profile.getAge()));
       txt_poition_v.setText(select_profile.getPosition());
       txt_id_v.setText(select_profile.getId());
       txt_level_v.setText(select_profile.getLevel());
       txt_gender_v.setText(select_profile.getGender());
       txt_email_v.setText(select_profile.getEmail());
       txt_cell_v.setText(String.valueOf(select_profile.getPhone()));
       txt_start_v.setText(select_profile.getStart_date());
       txt_team_v.setText(select_profile.getTeam_info());
       lbl_photo_v.setIcon(ResizeImage(select_profile.getPhoto()));
       
       
        
       
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int selected_row_idx =  profile_tbl.getSelectedRow();
       if(selected_row_idx<0){
           JOptionPane.showMessageDialog(this,"Please select a row to View");
           return;
       }
        DefaultTableModel model = (DefaultTableModel) profile_tbl.getModel();
       employee_profile select_profile = (employee_profile)model.getValueAt(selected_row_idx,0);
       
     String name = txt_name_v.getText()  ;
     String gender = txt_gender_v.getText();
     String id = txt_id_v.getText();
     int age = Integer.parseInt(txt_age_v.getText());
     String start_date = txt_start_v.getText();
     String level= txt_level_v.getText();
     String team_info = txt_team_v.getText();
     String position = txt_poition_v.getText();
     long phone = Integer.parseInt(txt_cell_v.getText());
     String email = txt_email_v.getText();
      
    
     
      if(name.equals("")){
        JOptionPane.showMessageDialog(this, "Please Add Name");
     }
     else if(gender.equals("")){
         JOptionPane.showMessageDialog(this, "Please Select Gender..");
     }
     else if(id.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add ID..");
     }
    
     else if(start_date.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add Start Date..");
     }
     else if(level.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add Level..");
     }
     else if(team_info.equals("")){
        JOptionPane.showMessageDialog(this, "Please Add Team Info..");
     }
     else if(position.equals("")){
         JOptionPane.showMessageDialog(this, "Please Add Position..");
     }
     
     
     else if(email.equals("")){
        JOptionPane.showMessageDialog(this, "Please Add E-mail..");
     }
     
     
     else if(!name.equals("")&& !gender.equals("") && !id.equals("") && !start_date.equals("") && 
             !level.equals("") || level.equals("Manager") || level.equals("Junior") || level.equals("Level 2") || level.equals("Level 3") || level.equals("Senior") 
             || level.equals("Sr Maneger") || level.equals("Associate") &&!team_info.equals("") && !position.equals("") && !email.equals("") && !team_info.equals("")&& !position.equals("") && !email.equals(""))
     {
     employee_profile ep = e_list.addnewEmployee();
     ep.setName(name);
     ep.setAge(age);
     ep.setId(id);
     ep.setLevel(level);
     ep.setStart_date(start_date);
     ep.setTeam_info(team_info);
     ep.setPosition(position);
     ep.setPhone(phone);
     ep.setEmail(email);
     ep.setGender(gender);
     

     
     
       txt_name_v.setText(name);
       txt_age_v.setText(String.valueOf(age));
       txt_poition_v.setText(position);
       txt_id_v.setText(id);
       txt_level_v.setText(level);
       txt_gender_v.setText(gender);
       txt_email_v.setText(email);
       txt_cell_v.setText(String.valueOf(phone));
       txt_start_v.setText(start_date);
       txt_team_v.setText(team_info);
       lbl_photo_v.setIcon(ResizeImage(select_profile.getPhoto()));
       populate_table();
     }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) profile_tbl.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        profile_tbl.setRowSorter(tr );
        tr.setRowFilter(RowFilter.regexFilter(txt_search.getText().trim()));
        
      
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_cell_vKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cell_vKeyTyped
        // TODO add your handling code here:
         char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)) || enter== KeyEvent.VK_BACK_SPACE || enter== KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_cell_vKeyTyped

    private void txt_age_vKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_age_vKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)) || enter== KeyEvent.VK_BACK_SPACE || enter== KeyEvent.VK_DELETE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_age_vKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_employee_View;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_cell;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_level;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_photo_v;
    private javax.swing.JLabel lbl_position;
    private javax.swing.JLabel lbl_start_date;
    private javax.swing.JLabel lbl_team;
    private javax.swing.JTable profile_tbl;
    private javax.swing.JTextField txt_age_v;
    private javax.swing.JTextField txt_cell_v;
    private javax.swing.JTextField txt_email_v;
    private javax.swing.JTextField txt_gender_v;
    private javax.swing.JTextField txt_id_v;
    private javax.swing.JTextField txt_level_v;
    private javax.swing.JTextField txt_name_v;
    private javax.swing.JTextField txt_poition_v;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_start_v;
    private javax.swing.JTextField txt_team_v;
    // End of variables declaration//GEN-END:variables

    private void populate_table() {
       
        DefaultTableModel model = (DefaultTableModel) profile_tbl.getModel();
        model.setRowCount(0);
        for(employee_profile profile : e_list.getEmployee_list() ){
            
            Object[] row = new Object[4];
            row[0] = profile;
            row[1] = profile.getId();
            row[2] = profile.getGender();
            row[3] = profile.getTeam_info();
            
            
            model.addRow(row);
        }
    }
    
     public ImageIcon ResizeImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_photo_v.getWidth(), lbl_photo_v.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
     
     
}
