/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui_design;

import java_classes.Community_dir;
import java_classes.Doctors_dir;
import java_classes.Encounter_his;
import java_classes.Hospital_dir;
import java_classes.Person_dir;
import java_classes.Patient_dir;
import java_classes.System_dir;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shubhambagal
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    
   
    
    public MainJframe() {
        initComponents();
        per_list = new Person_dir();
        patient_list = new Patient_dir();
        doc_list = new Doctors_dir();
        hos_dir = new Hospital_dir();
        comm_dir = new Community_dir();
        sys_dir = new System_dir();
        enc_his = new Encounter_his();
    }
    
    Sign_up_form signUp;
    Sign_in signIn;
    Person_dir per_list;
    Patient_dir patient_list;
    Doctors_dir doc_list;
    Hospital_dir hos_dir;
    Community_dir comm_dir;
    System_dir sys_dir;
    Encounter_his enc_his;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_name_main = new javax.swing.JTextField();
        btn_sign_in = new javax.swing.JButton();
        text_password_main = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        userType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Apple LiSung", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_local_hospital_black_24dp.png"))); // NOI18N
        jLabel1.setLabelFor(main_panel);
        jLabel1.setText("Hospital System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_person_2_black_24dp.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_key_black_24dp.png"))); // NOI18N

        text_name_main.setText("User Name");
        text_name_main.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_name_mainFocusGained(evt);
            }
        });
        text_name_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_name_mainActionPerformed(evt);
            }
        });

        btn_sign_in.setText("Sign In");
        btn_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_inActionPerformed(evt);
            }
        });

        text_password_main.setText("jPasswordField1");
        text_password_main.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_password_mainFocusGained(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_person_2_black_24dp.png"))); // NOI18N

        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type ", "Patient", "Doctor", "Hospital", "Community", "System" }));

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_name_main)
                            .addComponent(text_password_main, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(userType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btn_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(userType))
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_name_main, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(text_password_main))
                .addGap(60, 60, 60)
                .addComponent(btn_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_name_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_name_mainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_name_mainActionPerformed

    private void text_name_mainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_name_mainFocusGained
        // TODO add your handling code here:
        text_name_main.setText("");
    }//GEN-LAST:event_text_name_mainFocusGained

    private void text_password_mainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_password_mainFocusGained
        // TODO add your handling code here:
        text_password_main.setText("");
    }//GEN-LAST:event_text_password_mainFocusGained

    private void btn_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_inActionPerformed
        // TODO add your handling code here:
        String user, pass;
        user = text_name_main.getText();
        pass = text_password_main.getText();
        
        if(userType.getSelectedItem().equals("System")){
              if(user.equals("admin")&&pass.equals("adminpass")){
             signUp = new Sign_up_form(per_list,patient_list,doc_list,hos_dir,comm_dir,sys_dir,enc_his);
        signUp.setVisible(true);
        signUp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        }
              else{

            JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
        }
            
       
       
       
        }
        
        else if(userType.getSelectedItem().equals("Doctor")){
            
    
            
                 signIn = new Sign_in(per_list,text_name_main.getText(),text_password_main.getText(),userType.getSelectedItem().toString(),patient_list,comm_dir,hos_dir,doc_list,enc_his);
        
            signIn.setVisible(true);
        
            signIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
            
             
           
    
        }
        
        else if(userType.getSelectedItem().equals("Hospital")){
            if(user.equals("hos")&&pass.equals("hospass")){
                 signIn = new Sign_in(per_list,text_name_main.getText(),text_password_main.getText(),userType.getSelectedItem().toString(),patient_list,comm_dir,hos_dir,doc_list,enc_his);
        
            signIn.setVisible(true);
        
            signIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
            }
            
              else{

            JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
       
            }
    
    
        }
        
        else if(userType.getSelectedItem().equals("Community")){
            if(user.equals("comm")&&pass.equals("commpass")){
                 signIn = new Sign_in(per_list,text_name_main.getText(),text_password_main.getText(),userType.getSelectedItem().toString(),patient_list,comm_dir,hos_dir,doc_list,enc_his);
        
            signIn.setVisible(true);
        
            signIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
            }
            
              else{

            JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
       
            }
    
    
        }
        
        else if(userType.getSelectedItem().equals("Patient")){
            
            signIn = new Sign_in(per_list,text_name_main.getText(),text_password_main.getText(),userType.getSelectedItem().toString(),patient_list,comm_dir,hos_dir,doc_list,enc_his);
        
           
            
            signIn.setVisible(true);
        
            signIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
    
        }
        
        
        
        
            
        
            
        
        
        
        
    }//GEN-LAST:event_btn_sign_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sign_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField text_name_main;
    private javax.swing.JPasswordField text_password_main;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
