/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui_design;

import java_classes.community;
import java_classes.doctor;
import java_classes.hospital;
import java_classes.patient;
import java_classes.person;
import java_classes.system;
import javax.swing.JOptionPane;

/**
 *
 * @author shubhambagal
 */
public class sign_up_form extends javax.swing.JFrame {

    /**
     * Creates new form sign_up_form
     */
    public sign_up_form() {
        initComponents();
         patient_sign_up.setVisible(false);
         doctor_sign_up.setVisible(false);
         hospital_sign_up.setVisible(false);
         community_sign_up.setVisible(false);
         system_sign_up.setVisible(false);
         person = new person();
         patient = new patient();
         doctor = new doctor();
         community = new community();
         hos  = new hospital();
         sys = new system();
         
    }

    patient patient;
    doctor doctor;
    person person;
    community community;
    hospital hos;
    system sys;
    
    String user_type;
    String user_name;
    String user_password;
    String user_address;
    String patient_ssn;
    String patient_city;
    String patient_communtiy;
    String patient_house;
    String patient_age;
    String doc_city;
    String doc_ssn;
    String doc_community;
    String doc_hospital;
    String commu_name;
    String commu_city;
    String commu_position;
    String hos_name;
    String hos_city;
    String hos_commu;
    String sys_id;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        common_sign_up_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_name_sign_up = new javax.swing.JTextField();
        text_address_sign_up = new javax.swing.JTextField();
        text_password_sign_up = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combox_sign_up = new javax.swing.JComboBox<>();
        coustamized_sign_up_panel = new javax.swing.JLayeredPane();
        patient_sign_up = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_signUp_per_ssn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_signUp_per_city = new javax.swing.JTextField();
        txt_signUp_per_commu = new javax.swing.JTextField();
        txt_signUp_per_house = new javax.swing.JTextField();
        btn_patient_add = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txt_signUp_per_age = new javax.swing.JTextField();
        doctor_sign_up = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_signUp_doc_ssn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_signUp_doc_city = new javax.swing.JTextField();
        txt_sign_up_doc_commu = new javax.swing.JTextField();
        txt_signUp_doc_hos = new javax.swing.JTextField();
        btn_signUp_doc_add = new javax.swing.JButton();
        community_sign_up = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        text_sign_up_com_city = new javax.swing.JTextField();
        text_signUp_com_pos = new javax.swing.JTextField();
        btn_com_add = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        text_signUp_com_commu = new javax.swing.JTextField();
        hospital_sign_up = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        text_sign_up_hos_city = new javax.swing.JTextField();
        text_signUp_hos_commu = new javax.swing.JTextField();
        btn_hos_add = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        text_signUp_hos_name = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        system_sign_up = new javax.swing.JPanel();
        text_signUp_sys_id = new javax.swing.JTextField();
        btn_sys_add = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sign Up Form");

        jLabel2.setText("User Name");

        jLabel3.setText("Address");

        jLabel4.setText("Password");

        jLabel5.setText("User Name");

        combox_sign_up.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Patient", "Doctor", "Hospital", "Community", "System", " " }));
        combox_sign_up.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combox_sign_upItemStateChanged(evt);
            }
        });
        combox_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_sign_upActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout common_sign_up_panelLayout = new javax.swing.GroupLayout(common_sign_up_panel);
        common_sign_up_panel.setLayout(common_sign_up_panelLayout);
        common_sign_up_panelLayout.setHorizontalGroup(
            common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(common_sign_up_panelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(common_sign_up_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combox_sign_up, 0, 167, Short.MAX_VALUE)
                            .addComponent(text_address_sign_up)
                            .addComponent(text_name_sign_up)
                            .addComponent(text_password_sign_up))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(common_sign_up_panelLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        common_sign_up_panelLayout.setVerticalGroup(
            common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(common_sign_up_panelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_name_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_address_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_password_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(common_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel6.setText("SSN no.");

        jLabel7.setText("City");

        jLabel8.setText("Community");

        jLabel9.setText("House");

        btn_patient_add.setText("Add Details");
        btn_patient_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patient_addActionPerformed(evt);
            }
        });
        btn_patient_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_patient_addKeyReleased(evt);
            }
        });

        jLabel20.setText("Age");

        javax.swing.GroupLayout patient_sign_upLayout = new javax.swing.GroupLayout(patient_sign_up);
        patient_sign_up.setLayout(patient_sign_upLayout);
        patient_sign_upLayout.setHorizontalGroup(
            patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_sign_upLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patient_sign_upLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_signUp_per_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patient_sign_upLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_signUp_per_city, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patient_sign_upLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(txt_signUp_per_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patient_sign_upLayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_signUp_per_house, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_patient_add, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_signUp_per_age, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        patient_sign_upLayout.setVerticalGroup(
            patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_sign_upLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_per_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_per_city, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_per_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_per_house, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patient_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_per_age, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_patient_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jLabel10.setText("SSN no.");

        jLabel11.setText("City");

        jLabel12.setText("Community");

        jLabel13.setText("Hospital ");

        btn_signUp_doc_add.setText("Add Details");
        btn_signUp_doc_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUp_doc_addActionPerformed(evt);
            }
        });
        btn_signUp_doc_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_signUp_doc_addKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout doctor_sign_upLayout = new javax.swing.GroupLayout(doctor_sign_up);
        doctor_sign_up.setLayout(doctor_sign_upLayout);
        doctor_sign_upLayout.setHorizontalGroup(
            doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctor_sign_upLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_signUp_doc_hos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sign_up_doc_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_doc_city, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_doc_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signUp_doc_add, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        doctor_sign_upLayout.setVerticalGroup(
            doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctor_sign_upLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_doc_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_doc_city, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sign_up_doc_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(doctor_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signUp_doc_hos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btn_signUp_doc_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel14.setText("City");

        jLabel15.setText("Admin Position");

        btn_com_add.setText("Add Details");
        btn_com_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_com_addActionPerformed(evt);
            }
        });
        btn_com_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_com_addKeyReleased(evt);
            }
        });

        jLabel17.setText("Community");

        javax.swing.GroupLayout community_sign_upLayout = new javax.swing.GroupLayout(community_sign_up);
        community_sign_up.setLayout(community_sign_upLayout);
        community_sign_upLayout.setHorizontalGroup(
            community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(community_sign_upLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_signUp_com_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_sign_up_com_city, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_com_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_com_add, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        community_sign_upLayout.setVerticalGroup(
            community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(community_sign_upLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_com_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_sign_up_com_city, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(community_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_com_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btn_com_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jLabel16.setText("Community");

        btn_hos_add.setText("Add Details");
        btn_hos_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hos_addActionPerformed(evt);
            }
        });
        btn_hos_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_hos_addKeyReleased(evt);
            }
        });

        jLabel18.setText("Hospital Name");

        jLabel19.setText("City");

        javax.swing.GroupLayout hospital_sign_upLayout = new javax.swing.GroupLayout(hospital_sign_up);
        hospital_sign_up.setLayout(hospital_sign_upLayout);
        hospital_sign_upLayout.setHorizontalGroup(
            hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospital_sign_upLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_signUp_hos_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_sign_up_hos_city, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_hos_name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hos_add, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        hospital_sign_upLayout.setVerticalGroup(
            hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospital_sign_upLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_hos_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_sign_up_hos_city, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hospital_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_hos_commu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btn_hos_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        btn_sys_add.setText("Add Details");
        btn_sys_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sys_addActionPerformed(evt);
            }
        });
        btn_sys_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_sys_addKeyReleased(evt);
            }
        });

        jLabel22.setText("System ID");

        javax.swing.GroupLayout system_sign_upLayout = new javax.swing.GroupLayout(system_sign_up);
        system_sign_up.setLayout(system_sign_upLayout);
        system_sign_upLayout.setHorizontalGroup(
            system_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(system_sign_upLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(system_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_signUp_sys_id, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sys_add, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        system_sign_upLayout.setVerticalGroup(
            system_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(system_sign_upLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(system_sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_signUp_sys_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167)
                .addComponent(btn_sys_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        coustamized_sign_up_panel.setLayer(patient_sign_up, javax.swing.JLayeredPane.DEFAULT_LAYER);
        coustamized_sign_up_panel.setLayer(doctor_sign_up, javax.swing.JLayeredPane.DEFAULT_LAYER);
        coustamized_sign_up_panel.setLayer(community_sign_up, javax.swing.JLayeredPane.DEFAULT_LAYER);
        coustamized_sign_up_panel.setLayer(hospital_sign_up, javax.swing.JLayeredPane.DEFAULT_LAYER);
        coustamized_sign_up_panel.setLayer(system_sign_up, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout coustamized_sign_up_panelLayout = new javax.swing.GroupLayout(coustamized_sign_up_panel);
        coustamized_sign_up_panel.setLayout(coustamized_sign_up_panelLayout);
        coustamized_sign_up_panelLayout.setHorizontalGroup(
            coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patient_sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(doctor_sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(community_sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(hospital_sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(system_sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coustamized_sign_up_panelLayout.setVerticalGroup(
            coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patient_sign_up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(doctor_sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(community_sign_up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(hospital_sign_up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(coustamized_sign_up_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(system_sign_up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(common_sign_up_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(coustamized_sign_up_panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(common_sign_up_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coustamized_sign_up_panel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combox_sign_upItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combox_sign_upItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combox_sign_upItemStateChanged

    private void combox_sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_sign_upActionPerformed
        // TODO add your handling code here:
         
         
         
         
        switch (combox_sign_up.getSelectedItem().toString()) {
            case "Patient" -> {
                
                patient_sign_up.setVisible(true);
                doctor_sign_up.setVisible(false);
                hospital_sign_up.setVisible(false);
                community_sign_up.setVisible(false);
                system_sign_up.setVisible(false);
                
                JOptionPane.showMessageDialog(this, "Selected user is :" + combox_sign_up.getSelectedItem().toString());
            }
                
            case "Doctor" -> {
                patient_sign_up.setVisible(false);
                doctor_sign_up.setVisible(true);
                hospital_sign_up.setVisible(false);
                community_sign_up.setVisible(false);
                system_sign_up.setVisible(false);
                JOptionPane.showMessageDialog(this, "Selected user is :" + combox_sign_up.getSelectedItem().toString());
            }
            case "Hospital" -> {
                patient_sign_up.setVisible(false);
                doctor_sign_up.setVisible(false);
                hospital_sign_up.setVisible(true);
                community_sign_up.setVisible(false);
                system_sign_up.setVisible(false); JOptionPane.showMessageDialog(this, "Selected user is :" + combox_sign_up.getSelectedItem().toString());
            }
                
            case "Community" -> { 
                patient_sign_up.setVisible(false);
                doctor_sign_up.setVisible(false);
                hospital_sign_up.setVisible(false);
                community_sign_up.setVisible(true);
                system_sign_up.setVisible(false);
                JOptionPane.showMessageDialog(this, "Selected user is :" + combox_sign_up.getSelectedItem().toString());
            }
                
            case "System" -> {
                 patient_sign_up.setVisible(false);
                doctor_sign_up.setVisible(false);
                hospital_sign_up.setVisible(false);
                community_sign_up.setVisible(false);
                system_sign_up.setVisible(true);
                JOptionPane.showMessageDialog(this, "Selected user is :" + combox_sign_up.getSelectedItem().toString());
            }
            default -> {
                
            }
        }
         
        






    }//GEN-LAST:event_combox_sign_upActionPerformed

    private void btn_com_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_com_addActionPerformed
        // TODO add your handling code here:
        user_type =  combox_sign_up.getSelectedItem().toString();
        user_name  = text_name_sign_up.getText();
        user_password = text_password_sign_up.getText();
        user_address =text_address_sign_up.getText() ;
        person.setName(user_name);
        person.setUser_type(user_type);
        person.setPassword(user_password);
        person.setAddress(user_address);
        
        commu_name = text_signUp_com_commu.getText();
        commu_city = text_sign_up_com_city.getText();
        commu_position = text_signUp_com_pos.getText();
        
        community.setCommunity(commu_name);
        community.setCity(commu_city);
        community.setAdmin_position(commu_position);
        
        JOptionPane.showMessageDialog(this,  combox_sign_up.getSelectedItem().toString()+" Details Added Successfully" );
        
    }//GEN-LAST:event_btn_com_addActionPerformed

    private void btn_hos_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hos_addActionPerformed
        // TODO add your handling code here:
         user_type =  combox_sign_up.getSelectedItem().toString();
        user_name  = text_name_sign_up.getText();
        user_password = text_password_sign_up.getText();
        user_address =text_address_sign_up.getText() ;
        person.setName(user_name);
        person.setUser_type(user_type);
        person.setPassword(user_password);
        person.setAddress(user_address);
        
        hos_name = text_signUp_hos_name.getText().toString();
        hos_city = text_sign_up_hos_city.getText();
        hos_commu = text_signUp_hos_commu.getText();
        
        hos.setCity(hos_city);
        hos.setCommunity(hos_commu);
        hos.setHospital_community(hos_name);
        
         JOptionPane.showMessageDialog(this,  combox_sign_up.getSelectedItem().toString()+" Details Added Successfully" );
        
        
    }//GEN-LAST:event_btn_hos_addActionPerformed

    private void btn_sys_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sys_addActionPerformed
        // TODO add your handling code here:
        user_type =  combox_sign_up.getSelectedItem().toString();
        user_name  = text_name_sign_up.getText();
        user_password = text_password_sign_up.getText();
        user_address =text_address_sign_up.getText() ;
        person.setName(user_name);
        person.setUser_type(user_type);
        person.setPassword(user_password);
        person.setAddress(user_address);
        
        sys_id= text_signUp_sys_id.getText().toString();
        
        sys.setSystem_id(sys_id);
        
         JOptionPane.showMessageDialog(this,  combox_sign_up.getSelectedItem().toString()+" Details Added Successfully" );
        
    }//GEN-LAST:event_btn_sys_addActionPerformed

    private void btn_patient_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_patient_addKeyReleased
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btn_patient_addKeyReleased

    private void btn_signUp_doc_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_signUp_doc_addKeyReleased
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_btn_signUp_doc_addKeyReleased

    private void btn_com_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_com_addKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_com_addKeyReleased

    private void btn_hos_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_hos_addKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_hos_addKeyReleased

    private void btn_sys_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_sys_addKeyReleased
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btn_sys_addKeyReleased

    private void btn_patient_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patient_addActionPerformed
        // TODO add your handling code here:
        user_type =  combox_sign_up.getSelectedItem().toString();
        user_name  = text_name_sign_up.getText();
        user_password = text_password_sign_up.getText();
        user_address =text_address_sign_up.getText() ;
        patient_ssn = txt_signUp_per_ssn.getText();
        patient_city = txt_signUp_per_city.getText();
        patient_communtiy = txt_signUp_per_commu.getText();
        patient_house = txt_signUp_per_house.getText();
        patient_age = txt_signUp_per_age.getText().toString();
        
        
        person.setName(user_name);
        person.setUser_type(user_type);
        person.setPassword(user_password);
        person.setAddress(user_address);
        patient.setSsn(patient_ssn);
        patient.setCity(patient_city);
        patient.setHousse(patient_house);
        patient.setAge(patient_age);
        patient.setCommunity(patient_communtiy);
        
         JOptionPane.showMessageDialog(this,  combox_sign_up.getSelectedItem().toString()+" Details Added Successfully" );
        
        
    }//GEN-LAST:event_btn_patient_addActionPerformed

    private void btn_signUp_doc_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUp_doc_addActionPerformed
        // TODO add your handling code here:
        
        user_type =  combox_sign_up.getSelectedItem().toString();
        user_name  = text_name_sign_up.getText();
        user_password = text_password_sign_up.getText();
        user_address =text_address_sign_up.getText() ;
        person.setName(user_name);
        person.setUser_type(user_type);
        person.setPassword(user_password);
        person.setAddress(user_address);
        doc_city =  text_sign_up_hos_city.getText();
        doc_ssn = txt_signUp_doc_ssn.getText();
        doc_community= txt_sign_up_doc_commu.getText();
        doc_hospital = txt_signUp_doc_hos.getText();
        
        
        doctor.setSsn(doc_ssn);
        doctor.setCity(doc_city);
        doctor.setCommunity(doc_community);
        doctor.setHospital(doc_hospital);
        
         JOptionPane.showMessageDialog(this,  combox_sign_up.getSelectedItem().toString()+" Details Added Successfully" );
    }//GEN-LAST:event_btn_signUp_doc_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_com_add;
    private javax.swing.JButton btn_hos_add;
    private javax.swing.JButton btn_patient_add;
    private javax.swing.JButton btn_signUp_doc_add;
    private javax.swing.JButton btn_sys_add;
    private javax.swing.JComboBox<String> combox_sign_up;
    private javax.swing.JPanel common_sign_up_panel;
    private javax.swing.JPanel community_sign_up;
    private javax.swing.JLayeredPane coustamized_sign_up_panel;
    private javax.swing.JPanel doctor_sign_up;
    private javax.swing.JPanel hospital_sign_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel patient_sign_up;
    private javax.swing.JPanel system_sign_up;
    private javax.swing.JTextField text_address_sign_up;
    private javax.swing.JTextField text_name_sign_up;
    private javax.swing.JTextField text_password_sign_up;
    private javax.swing.JTextField text_signUp_com_commu;
    private javax.swing.JTextField text_signUp_com_pos;
    private javax.swing.JTextField text_signUp_hos_commu;
    private javax.swing.JTextField text_signUp_hos_name;
    private javax.swing.JTextField text_signUp_sys_id;
    private javax.swing.JTextField text_sign_up_com_city;
    private javax.swing.JTextField text_sign_up_hos_city;
    private javax.swing.JTextField txt_signUp_doc_city;
    private javax.swing.JTextField txt_signUp_doc_hos;
    private javax.swing.JTextField txt_signUp_doc_ssn;
    private javax.swing.JTextField txt_signUp_per_age;
    private javax.swing.JTextField txt_signUp_per_city;
    private javax.swing.JTextField txt_signUp_per_commu;
    private javax.swing.JTextField txt_signUp_per_house;
    private javax.swing.JTextField txt_signUp_per_ssn;
    private javax.swing.JTextField txt_sign_up_doc_commu;
    // End of variables declaration//GEN-END:variables
}
